#!/usr/bin/env sh
SKETCHYBAR_PID=""

cleanup() {
    echo "Cleaning up..."
    if [ -n "$SKETCHYBAR_PID" ]; then
        kill "$SKETCHYBAR_PID" 2>/dev/null
    fi
}

# Only trap SIGTERM and SIGINT, not EXIT
trap cleanup SIGTERM SIGINT

# Your existing yabai setup
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=shutdown action="pkill -x sketchybar" label="Kill SketchyBar with Yabai"

# Function to apply Yabai configuration settings
apply_yabai_config() {
  local yabai_config=(
    -m config

    layout bsp
    auto_balance off
    split_ratio 0.50

    insert_feedback_color 0xff9dd274

    focus_follows_mouse off
    mouse_follows_focus off
    mouse_modifier ctrl
    mouse_action1 move
    mouse_action2 resize
    mouse_drop_action swap

    top_padding 8
    bottom_padding 8
    left_padding 8
    right_padding 9
    window_gap 8
    external_bar all:36:0

    active_window_opacity 1.0
    normal_window_opacity 1.0
    
    window_placement second_child
    window_shadow float
    window_opacity on
    window_opacity_duration 0.2
    window_zoom_persist off
    window_animation_duration 0.3
    window_animation_easing ease_out_quint
  )

  yabai "${yabai_config[@]}"
}

# function to add application-specific rules
add_yabai_rules() {
  # specific applications with custom opacity settings
  yabai -m rule --add app="^Cursor$" opacity=0.9
  yabai -m rule --add app="^Visual Studio Code$" opacity=0.9
  yabai -m rule --add app="^kitty$" opacity=0.9

  # exclude specific applications from being managed
  apps_to_exclude=(
    "^calculator$"
    "^Software Update$"
    "^Dictionary$"
    "^System Preferences$"
    "^System Settings$"
    "^System Information"
    "^Archive Utility$"
    "^App Store$"
    "^Raycast$"
    "^activity monitor$"
    "^Messages$"
    "^Logi Options+$"
  )

  for app in "${apps_to_exclude[@]}"; do
    yabai -m rule --add app="$app" manage=off
  done

  # Global Rules
  yabai -m rule --add app=".*" sub-layer=normal
  yabai -m rule --apply
}

# apply configuration and rules
apply_yabai_config
add_yabai_rules

# Start SketchyBar and store its PID
SKETCHYBAR_PATH="/opt/homebrew/bin/sketchybar"

if ! pgrep -x "sketchybar" >/dev/null; then
    echo "Starting SketchyBar..."
    "$SKETCHYBAR_PATH" &
    SKETCHYBAR_PID=$!
    sleep 1
fi

echo "yabai configuration loaded..."
