config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_starship.toml:
    src: config/starship.toml
    dst: ~/.config/starship.toml
  d_lazygit:
    src: config/lazygit
    dst: ~/.config/lazygit
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  d_macchina:
    src: config/macchina
    dst: ~/.config/macchina
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  f_wezterm.lua:
    src: wezterm.lua
    dst: "{{@@ home_dir @@}}/.wezterm.lua"
    chmod: "777"
  d_zsh:
    src: zsh
    dst: ~/.zsh
    template: true
profiles:
  common:
    dotfiles:
      - f_starship.toml
      - f_zshrc
      - d_macchina
      - d_nvim
      - d_zsh
      - f_wezterm.lua
  Jennys-MacBook-Pro.local:
    include:
      - common
    variables:
      distro: macos
      home_dir: $HOME
  Jennys-Josef-Laptop.local:
    include:
      - common
    variables:
      distro: macos
      home_dir: $HOME
  jonks-pi:
    variables:
      distro: debian
      home_dir: $HOME
    include:
      - common
  jingjing-gaming:
    variables:
      distro: wslarch
      home_dir: "%HOME%"
    include:
      - common
