config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_starship.toml:
    src: config/starship.toml
    dst: ~/.config/starship.toml
  d_lazygit:
    src: config/lazygit
    dst: ~/.config/lazygit
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  d_macchina:
    src: config/macchina
    dst: ~/.config/macchina
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  f_wezterm.lua:
    src: wezterm.lua
    dst: "{{@@ home_dir @@}}/.wezterm.lua"
    chmod: "777"
  d_zsh:
    src: zsh
    dst: ~/.zsh
    template: true
  d_pypoetry:
    src: config/pypoetry
    dst: ~/.config/pypoetry
  d_nushell:
    src: config/nushell
    dst: "{{@@ nu_dir @@}}"
  d_fish:
    src: config/fish
    dst: ~/.config/fish
    chmod: "700"
profiles:
  common:
    dotfiles:
      - f_starship.toml
      - f_zshrc
      - d_macchina
      - d_nvim
      - d_zsh
      - d_pypoetry
      - f_wezterm.lua
      - d_nushell
      - d_fish
  Jennys-MacBook-Pro.local:
    include:
      - common
    dynvariables:
      nu_dir: nu -c '$nu.default-config-dir'
    variables:
      distro: macos
      home_dir: "~"
  jonks-pi:
    variables:
      distro: debian
      home_dir: "~"
    include:
      - common
  jingjing-gaming:
    variables:
      distro: wslarch
      home_dir: /mnt/c/Users/jingj
    dynvariables:
      nu_dir: nu -c '$nu.default-config-dir'
    include:
      - common
  M1224:
    include:
      - common
    variables:
      distro: macos
      home_dir: "~"
    dynvariables:
      nu_dir: nu -c '$nu.default-config-dir'
