# Jonk 

spacing         = 3
prefer_small_ascii = false
key_color       = "#cba6f7"
separator       = ""

[box]
border          = "plain"

[palette]
type            = "Full"
glyph           = "●   "
visible         = true

[bar]
glyph           = "●"
hide_delimiters = true
visible         = true

[box.inner_margin]
x               = 2
y               = 1

[custom_ascii]
color           = "#fab387"

